version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000/api/v1
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
    # Add --host to allow connections from outside the container
    command: npm run dev -- --host

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres/moviedb
      - SECRET_KEY=your-secret-key-here
      - CORS_ORIGINS=http://localhost:5173
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=moviedb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
